const LS_KEY='berkah_products_v1';
const ADMIN_SESSION='berkah_admin_unlocked';
const categories=["EZY","AKAKO","TABITHA"];
function seedIfEmpty(){ if(localStorage.getItem(LS_KEY)) return; const arr=[]; for(let i=1;i<=50;i++){ arr.push({id:i,title:`Produk ${i}`,price:10000+i*5000,desc:`Deskripsi Produk ${i}`,category:categories[i%3],seller:'BERKAH SETIA MAJU',images:['assets/sample-product.png']}); } localStorage.setItem(LS_KEY,JSON.stringify(arr)); }
seedIfEmpty();
let products=JSON.parse(localStorage.getItem(LS_KEY))||[];
function renderCategories(){ const bar=document.getElementById('categoryBar'); bar.innerHTML=''; const all=document.createElement('div'); all.className='category active'; all.textContent='Semua'; all.onclick=()=>filterByCategory(null); bar.appendChild(all); categories.forEach(c=>{ const el=document.createElement('div'); el.className='category'; el.textContent=c; el.onclick=()=>filterByCategory(c); bar.appendChild(el); }); }
renderCategories();
let activeCategory=null;
function filterByCategory(cat){ activeCategory=cat; document.querySelectorAll('.category').forEach(ch=>ch.classList.remove('active')); Array.from(document.querySelectorAll('.category')).find(n=>n.textContent===(cat||'Semua')).classList.add('active'); renderProducts(); }
function renderProducts(){ products=JSON.parse(localStorage.getItem(LS_KEY))||[]; const grid=document.getElementById('productGrid'); grid.innerHTML=''; const q=document.getElementById('searchBar').value.toLowerCase(); const list=products.filter(p=>{ if(activeCategory && p.category!==activeCategory) return false; if(q && !(p.title.toLowerCase().includes(q) || p.desc.toLowerCase().includes(q))) return false; return true; }); list.slice(0,10).forEach(p=>{ const card=document.createElement('div'); card.className='card fade-up'; card.innerHTML=`<div class="img-wrap"><img src="${p.images[0]}"></div><h4>${p.title}</h4><p class="small">${p.category} • ${p.seller}</p><div class="price">Rp ${Number(p.price).toLocaleString()}</div><div class="meta"><button class="btn btn-primary" onclick="openModal(${p.id},event)">Lihat Produk</button></div>`; grid.appendChild(card); }); }
document.getElementById('searchBar').addEventListener('input', renderProducts);
renderProducts();
function openModal(id,e){ if(e) e.stopPropagation(); const p=products.find(x=>x.id===id); if(!p) return alert('Tidak ditemukan'); showModal(p); }
function showModal(p){ document.getElementById('modalMain').src=p.images[0]||''; document.getElementById('modalTitle').textContent=p.title; document.getElementById('modalDesc').textContent=p.desc; document.getElementById('modalPrice').textContent='Rp '+Number(p.price).toLocaleString(); document.getElementById('modalSeller').textContent='Penjual: '+p.seller; const thumbs=document.getElementById('thumbs'); thumbs.innerHTML=''; (p.images||[]).forEach((u,idx)=>{ const im=document.createElement('img'); im.src=u; im.onclick=()=>{ document.getElementById('modalMain').src=u; Array.from(thumbs.children).forEach(t=>t.classList.remove('active')); im.classList.add('active'); }; if(idx===0) im.classList.add('active'); thumbs.appendChild(im); }); document.getElementById('overlay').style.display='flex'; }
function closeModal(){ document.getElementById('overlay').style.display='none'; }
if(sessionStorage.getItem(ADMIN_SESSION)==='true'){ document.getElementById('adminPanel').classList.add('visible'); document.getElementById('adminPanel').setAttribute('aria-hidden','false'); }
document.addEventListener('keydown', function(e){ if(e.ctrlKey && e.shiftKey && e.key.toLowerCase()==='b'){ const panel=document.getElementById('adminPanel'); panel.classList.toggle('visible'); const vis=panel.classList.contains('visible'); panel.setAttribute('aria-hidden', vis?'false':'true'); if(vis) sessionStorage.setItem(ADMIN_SESSION,'true'); else sessionStorage.removeItem(ADMIN_SESSION); }});
function openAdmin(){ const pass=prompt('Masukkan password admin:'); const PW='12345'; if(pass===PW){ const panel=document.getElementById('adminPanel'); panel.classList.add('visible'); panel.setAttribute('aria-hidden','false'); sessionStorage.setItem(ADMIN_SESSION,'true'); alert('Admin terbuka'); } else alert('Password salah'); }
function lockAdmin(){ const panel=document.getElementById('adminPanel'); panel.classList.remove('visible'); panel.setAttribute('aria-hidden','true'); sessionStorage.removeItem(ADMIN_SESSION); alert('Admin disembunyikan'); }
function renderAdminList(){ products=JSON.parse(localStorage.getItem(LS_KEY))||[]; const list=document.getElementById('adminList'); list.innerHTML=''; products.forEach((p,i)=>{ const div=document.createElement('div'); div.className='admin-item'; div.innerHTML=`<div><strong>${p.title}</strong><br><span class=\"small\">${p.category} • Rp ${Number(p.price).toLocaleString()}</span></div><div><button class=\"edit-btn\" onclick=\"openEdit(${p.id})\">Edit</button> <button class=\"delete-btn\" onclick=\"deleteProduct(${p.id})\">Hapus</button></div>`; list.appendChild(div); }); }
renderAdminList();
const adminForm=document.getElementById('adminForm'); const adminCategory=document.getElementById('adminCategory');
function populateAdminCat(){ adminCategory.innerHTML=''; categories.forEach(c=>{ const o=document.createElement('option'); o.value=c; o.textContent=c; adminCategory.appendChild(o); }) }

function populateEditCat(){ const sel=document.getElementById('editCategory'); if(!sel) return; sel.innerHTML=''; categories.forEach(c=>{ const o=document.createElement('option'); o.value=c; o.textContent=c; sel.appendChild(o); }) }

populateEditCat();
populateAdminCat();
adminForm.addEventListener('submit', async function(e){ e.preventDefault(); const title=document.getElementById('adminTitle').value.trim(); const price=Number(document.getElementById('adminPrice').value)||0; const desc=document.getElementById('adminDesc').value.trim(); const category=document.getElementById('adminCategory').value; const files=document.getElementById('adminImages').files; if(!title) return alert('Nama produk harus diisi'); if(files.length===0) return alert('Pilih minimal 1 gambar'); const urls=[]; for(let i=0;i<files.length;i++){ const f=files[i]; urls.push(URL.createObjectURL(f)); } const id=products.length?Math.max(...products.map(p=>p.id))+1:1; const newP={id,title,price,desc,category,seller:'BERKAH SETIA MAJU',images:urls}; products.unshift(newP); localStorage.setItem(LS_KEY,JSON.stringify(products)); adminForm.reset(); renderProducts(); renderAdminList(); alert('Produk berhasil ditambahkan (local).'); });
function deleteProduct(id){ if(!confirm('Yakin ingin menghapus produk ini?')) return; products=JSON.parse(localStorage.getItem(LS_KEY))||[]; products=products.filter(p=>p.id!==id); localStorage.setItem(LS_KEY,JSON.stringify(products)); renderProducts(); renderAdminList(); alert('Produk dihapus.'); }
let editingId=null;
function openEdit(id){ products=JSON.parse(localStorage.getItem(LS_KEY))||[]; const p=products.find(x=>x.id===id); if(!p) return alert('Produk tidak ditemukan'); editingId=id; document.getElementById('editTitle').value=p.title; document.getElementById('editPrice').value=p.price; document.getElementById('editDesc').value=p.desc; document.getElementById('editCategory').value=p.category; const preview=document.getElementById('editPreview'); preview.innerHTML=''; (p.images||[]).forEach(u=>{ const img=document.createElement('img'); img.src=u; img.style.height='60px'; img.style.marginRight='6px'; preview.appendChild(img); }); document.getElementById('modalEdit').style.display='flex'; }
document.getElementById('editForm').addEventListener('submit', function(e){ e.preventDefault(); const title=document.getElementById('editTitle').value.trim(); const price=Number(document.getElementById('editPrice').value)||0; const desc=document.getElementById('editDesc').value.trim(); const category=document.getElementById('editCategory').value; const files=document.getElementById('editImages').files; products=JSON.parse(localStorage.getItem(LS_KEY))||[]; const idx=products.findIndex(p=>p.id===editingId); if(idx===-1) return alert('Produk tidak ditemukan'); const urls=products[idx].images.slice(); if(files && files.length>0){ for(let i=0;i<files.length;i++){ urls.push(URL.createObjectURL(files[i])); } } products[idx].title=title; products[idx].price=price; products[idx].desc=desc; products[idx].category=category; products[idx].images=urls; localStorage.setItem(LS_KEY,JSON.stringify(products)); document.getElementById('modalEdit').style.display='none'; renderProducts(); renderAdminList(); alert('Perubahan disimpan.'); });
function closeEditModal(){ document.getElementById('modalEdit').style.display='none'; }
document.getElementById('exportBtn').addEventListener('click', function(){ const data=localStorage.getItem(LS_KEY)||'[]'; const blob=new Blob([data],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='products.json'; a.click(); URL.revokeObjectURL(url); });
document.getElementById('importBtn').addEventListener('click', ()=>document.getElementById('importFile').click());
document.getElementById('importFile').addEventListener('change', function(e){ const f=e.target.files[0]; if(!f) return; const r=new FileReader(); r.onload=()=>{ try{ const arr=JSON.parse(r.result); if(Array.isArray(arr)){ localStorage.setItem(LS_KEY,JSON.stringify(arr)); products=arr; renderProducts(); renderAdminList(); alert('Import sukses'); } else alert('JSON invalid'); } catch(err){ alert('Gagal import'); } }; r.readAsText(f); });

// overlay click to close when clicking outside modal
document.getElementById('overlay').addEventListener('click', function(e){
  if(e.target.id === 'overlay') closeModal();
});
// close modal with Escape key
document.addEventListener('keydown', function(e){ if(e.key === 'Escape'){ closeModal(); closeEditModal(); } });
